# Generated by Django 4.1.4 on 2023-03-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('documento', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('nivel_risco', models.CharField(choices=[('Baixo', 'Baixo'), ('Baixíssimo', 'Baixíssimo'), ('Médio', 'Médio'), ('Alto', 'Alto'), ('Altíssimo', 'Altíssimo')], max_length=100, verbose_name='Nível de Risco')),
                ('modelo_negocio', models.CharField(blank=True, choices=[('Sol Copérnico', 'Sol Copérnico'), ('Sol+', 'Sol+')], max_length=100, null=True, verbose_name='Modelo de Negócio')),
                ('tipo_proposta', models.CharField(blank=True, choices=[('Venda Única', 'Venda Única'), ('Limites de Crédito', 'Limites de Crédito')], max_length=40, null=True, verbose_name='Tipo de Proposta')),
                ('valor_proposta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Proposta')),
                ('valor_concedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Concedido')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
            ],
            options={
                'db_table': 'Analises',
            },
        ),
    ]
