# Generated by Django 4.1.4 on 2023-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analises',
            name='tipo_proposta',
            field=models.CharField(blank=True, choices=[('Venda Única', 'Venda Única'), ('Limite de Crédito', 'Limite de Crédito')], max_length=40, null=True, verbose_name='Tipo de Proposta'),
        ),
    ]
