# Generated by Django 4.1.4 on 2023-02-10 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('documento', models.CharField(blank=True, max_length=14, primary_key=True, serialize=False, verbose_name='Documento')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('nivel_risco', models.CharField(choices=[('Baixissimo', 'Baixissimo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Altissimo', 'Altissimo')], max_length=100, verbose_name='Nivel de risco')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('num_pedido', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Numero do pedido')),
                ('data_pedido', models.DateField(verbose_name='Data do pedido')),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do pedido')),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da entrada')),
                ('valor_parcelado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor parcelado')),
                ('qnt_parcelas', models.IntegerField(verbose_name='Quantidade de parcelas')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_parcelamento.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parcela', models.IntegerField(verbose_name='Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de vencimento')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('num_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_parcelamento.vendas')),
            ],
        ),
    ]
