# Generated by Django 4.1.4 on 2023-02-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelas',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
    ]
