# Generated by Django 4.1.4 on 2023-02-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0002_alter_parcelas_status_alter_vendas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nivel_risco',
            field=models.CharField(choices=[('Baixissimo', 'Baixissimo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Altissimo', 'Altissimo')], max_length=100, verbose_name='Nível de Risco'),
        ),
        migrations.AlterField(
            model_name='parcelas',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='parcelas',
            name='status',
            field=models.CharField(blank=True, choices=[('Em Atraso', 'Em Atraso'), ('Em Aberto', 'Em Aberto')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_pedido',
            field=models.DateField(verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='num_pedido',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Número do Pedido'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='qnt_parcelas',
            field=models.IntegerField(verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status do Pedido'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Entrada'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_parcelado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Parcelado'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pedido'),
        ),
    ]
