# Generated by Django 4.1.4 on 2023-02-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0003_alter_cliente_nivel_risco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_analise',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Análise'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='status',
            field=models.CharField(blank=True, choices=[('Entregue', 'Entregue'), ('Em processo de entrega', 'Em processo de entrega'), ('Aguardando expedição', 'Aguardando expedição'), ('Em processo triagem', 'Em processo triagem')], max_length=100, null=True, verbose_name='Status do Pedido'),
        ),
    ]
