# Generated by Django 4.1.4 on 2023-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0004_cliente_data_analise_alter_vendas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_analise',
        ),
        migrations.AddField(
            model_name='cliente',
            name='modelo_negocio',
            field=models.CharField(blank=True, choices=[('Sol Copérnico', 'Sol Copernico'), ('Sol+', 'Sol+')], max_length=100, null=True, verbose_name='Modelo de Negócio'),
        ),
    ]
