# Generated by Django 4.1.4 on 2023-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0006_alter_parcelas_data_vencimento_alter_parcelas_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_analise',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Análise'),
        ),
    ]
