# Generated by Django 4.1.4 on 2023-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0007_cliente_data_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Cliente'),
        ),
    ]
