# Generated by Django 4.1.4 on 2023-02-13 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0008_alter_cliente_documento_alter_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelas',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='parcelas',
            name='status',
            field=models.CharField(blank=True, choices=[('Em Atraso', 'Em Atraso'), ('Em Aberto', 'Em Aberto'), ('Pago', 'Pago'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_parcelamento.cliente', verbose_name='CPF/CNPJ'),
        ),
    ]
