# Generated by Django 4.1.4 on 2023-02-14 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0010_remove_vendas_documento_delete_parcelas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_pedido', models.CharField(default=None, max_length=10, unique=True, verbose_name='Número do Pedido')),
                ('data_pedido', models.DateField(verbose_name='Data do Pedido')),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pedido')),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Entrada')),
                ('valor_parcelado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Parcelado')),
                ('qnt_parcelas', models.IntegerField(verbose_name='Quantidade de Parcelas')),
                ('status', models.CharField(blank=True, choices=[('Entregue', 'Entregue'), ('Em processo de entrega', 'Em processo de entrega'), ('Aguardando expedição', 'Aguardando expedição'), ('Em processo triagem', 'Em processo triagem')], max_length=100, null=True, verbose_name='Status do Pedido')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_parcelamento.cliente', verbose_name='CPF/CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Cliente')),
                ('parcela', models.IntegerField(verbose_name='Parcela')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(blank=True, choices=[('Em Atraso', 'Em Atraso'), ('Em Aberto', 'Em Aberto'), ('Pago', 'Pago'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], max_length=100, null=True, verbose_name='Status')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('num_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_parcelamento.vendas')),
            ],
        ),
    ]
