# Generated by Django 4.1.4 on 2023-02-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0011_vendas_parcelas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parcelas',
            table='Players',
        ),
    ]
