# Generated by Django 4.1.4 on 2023-02-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0014_alter_parcelas_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='vendas',
            table='Vendas',
        ),
    ]
