# Generated by Django 4.1.4 on 2023-02-14 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0015_alter_cliente_table_alter_vendas_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='modelo_negocio',
            field=models.CharField(blank=True, choices=[('Sol Copérnico', 'Sol Copérnico'), ('Sol+', 'Sol+')], max_length=100, null=True, verbose_name='Modelo de Negócio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nivel_risco',
            field=models.CharField(choices=[('Baixíssimo', 'Baixissimo'), ('Médio', 'Medio'), ('Alto', 'Alto'), ('Altíssimo', 'Altissimo')], max_length=100, verbose_name='Nível de Risco'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_parcelamento.cliente', verbose_name='Nome Cliente'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_parcelado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Parcelado'),
        ),
    ]
