# Generated by Django 4.1.4 on 2023-02-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0017_alter_cliente_nivel_risco_alter_vendas_num_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelas',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='parcelas',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='parcelas',
            name='num_pedido',
        ),
        migrations.RemoveField(
            model_name='parcelas',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='parcelas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='parcelas',
            name='valor',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nivel_risco',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Baixissimo', 'Baixíssimo'), ('Medio', 'Médio'), ('Alto', 'Alto'), ('Altissimo', 'Altíssimo')], max_length=100, verbose_name='Nível de Risco'),
        ),
    ]
