# Generated by Django 4.1.4 on 2023-02-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0018_remove_parcelas_data_vencimento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcelas',
        ),
    ]
