# Generated by Django 4.1.4 on 2023-02-20 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0019_delete_parcelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_pedido', models.CharField(max_length=30, verbose_name='Número do Pedido')),
                ('nome_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Cliente')),
                ('parcela', models.IntegerField(verbose_name='Parcela')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(blank=True, choices=[('Em Atraso', 'Em Atraso'), ('Em Aberto', 'Em Aberto'), ('Pago', 'Pago'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], max_length=100, null=True, verbose_name='Status')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('id_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_parcelamento.vendas')),
            ],
            options={
                'db_table': 'Parcelas',
            },
        ),
    ]
