# Generated by Django 4.1.4 on 2023-02-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_parcelamento', '0020_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='status_venda',
            field=models.CharField(blank=True, choices=[('Em dia', 'Em dia'), ('Em atraso', 'Em atraso'), ('Renegociado', 'Renegociado')], max_length=100, null=True, verbose_name='Status da Venda'),
        ),
    ]
